function [T,D1_SPN_V,D1_SPN_spn_iNa_m_na,D1_SPN_spn_iNa_h_na,D1_SPN_spn_iK_m_k,D1_SPN_spn_iM_m,D1_SPN_spn_iCa_m_cat,D1_SPN_spn_CaBuffer_caConcentration,D1_SPN_spn_iKca_m_kca,D2_SPN_V,D2_SPN_spn_iNa_m_na,D2_SPN_spn_iNa_h_na,D2_SPN_spn_iK_m_k,D2_SPN_spn_iM_m,D2_SPN_spn_iCa_m_cat,D2_SPN_spn_CaBuffer_caConcentration,D2_SPN_spn_iKca_m_kca,D1_SPN_D1_SPN_spn_iGABA_d_gaba,D1_SPN_D1_SPN_spn_iGABA_s_gaba,D2_SPN_D1_SPN_spn_iGABA_d_gaba,D2_SPN_D1_SPN_spn_iGABA_s_gaba,D1_SPN_D2_SPN_spn_iGABA_d_gaba,D1_SPN_D2_SPN_spn_iGABA_s_gaba,D2_SPN_D2_SPN_spn_iGABA_d_gaba,D2_SPN_D2_SPN_spn_iGABA_s_gaba,D1_SPN_spn_iNa_i_Na,D1_SPN_spn_iK_i_k,D1_SPN_spn_iLeak_i_l,D1_SPN_spn_iM_i_m,D1_SPN_spn_iCa_i_cat,D1_SPN_spn_iKca_i_kca,D1_SPN_spn_iPoisson_g_poisson,D1_SPN_spn_iPoisson_I_poisson,D1_SPN_spn_ipfcPoisson_g_pfc_poisson,D1_SPN_spn_ipfcPoisson_I_pfc_poisson,D2_SPN_spn_iNa_i_Na,D2_SPN_spn_iK_i_k,D2_SPN_spn_iLeak_i_l,D2_SPN_spn_iM_i_m,D2_SPN_spn_iCa_i_cat,D2_SPN_spn_iKca_i_kca,D2_SPN_spn_iPoisson_g_poisson,D2_SPN_spn_iPoisson_I_poisson,D2_SPN_spn_ipfcPoisson_g_pfc_poisson,D2_SPN_spn_ipfcPoisson_I_pfc_poisson,D1_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN,D2_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN,D1_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN,D2_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN,D1_SPN_spn_iM_Qs_m,D1_SPN_spn_iPoisson_s_poisson,D1_SPN_spn_ipfcPoisson_s_pfc_poisson,D2_SPN_spn_iM_Qs_m,D2_SPN_spn_iPoisson_s_poisson,D2_SPN_spn_ipfcPoisson_s_pfc_poisson,D1_SPN_D1_SPN_spn_iGABA_nRndConn_gaba,D1_SPN_D1_SPN_spn_iGABA_indPre_gaba,D1_SPN_D1_SPN_spn_iGABA_netcon_gaba,D2_SPN_D1_SPN_spn_iGABA_nRndConn_gaba,D2_SPN_D1_SPN_spn_iGABA_indPre_gaba,D2_SPN_D1_SPN_spn_iGABA_netcon_gaba,D1_SPN_D2_SPN_spn_iGABA_nRndConn_gaba,D1_SPN_D2_SPN_spn_iGABA_indPre_gaba,D1_SPN_D2_SPN_spn_iGABA_netcon_gaba,D2_SPN_D2_SPN_spn_iGABA_nRndConn_gaba,D2_SPN_D2_SPN_spn_iGABA_indPre_gaba,D2_SPN_D2_SPN_spn_iGABA_netcon_gaba]=solve_ode

% ------------------------------------------------------------
% Parameters:
% ------------------------------------------------------------
params = load('params.mat','p');
p = params.p;
downsample_factor=p.downsample_factor;
dt=p.dt;
T=(p.tspan(1):dt:p.tspan(2))';
ntime=length(T);
nsamp=length(1:downsample_factor:ntime);

% the 'shuffle' random seed has been set in advance.

% ------------------------------------------------------------
% Fixed variables:
% ------------------------------------------------------------
D1_SPN_spn_iM_Qs_m =  p.D1_SPN_spn_iM_Q10_m^(.1*(p.D1_SPN_spn_iM_Tphysiol_m-p.D1_SPN_spn_iM_Tenv_m));
D1_SPN_spn_iPoisson_s_poisson = getPoissonDutyCycleGating(p.D1_SPN_spn_iPoisson_onset_poisson,p.D1_SPN_spn_iPoisson_offset_poisson,p.D1_SPN_spn_iPoisson_latency_poisson,p.D1_SPN_spn_iPoisson_f_poisson,p.D1_SPN_spn_iPoisson_fsigma_poisson,p.D1_SPN_spn_iPoisson_phi_poisson,p.D1_SPN_spn_iPoisson_connsigma_poisson,p.D1_SPN_spn_iPoisson_baseline_poisson,p.D1_SPN_spn_iPoisson_DC_poisson,p.D1_SPN_spn_iPoisson_AC_poisson,p.D1_SPN_spn_iPoisson_slopedutycycle_poisson,p.D1_SPN_spn_iPoisson_thresholddutycycle_poisson,p.D1_SPN_spn_iPoisson_tau_poisson,p.D1_SPN_spn_iPoisson_kick_poisson,T,p.D1_SPN_Npop);
D1_SPN_spn_ipfcPoisson_s_pfc_poisson = getPoissonDutyCycleGating(p.D1_SPN_spn_ipfcPoisson_onset_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_offset_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_latency_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_f_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_fsigma_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_phi_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_connsigma_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_baseline_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_DC_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_AC_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_slopedutycycle_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_thresholddutycycle_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_tau_pfc_poisson,p.D1_SPN_spn_ipfcPoisson_kick_pfc_poisson,T,p.D1_SPN_Npop);
D2_SPN_spn_iM_Qs_m =  p.D2_SPN_spn_iM_Q10_m^(.1*(p.D2_SPN_spn_iM_Tphysiol_m-p.D2_SPN_spn_iM_Tenv_m));
D2_SPN_spn_iPoisson_s_poisson = getPoissonDutyCycleGating(p.D2_SPN_spn_iPoisson_onset_poisson,p.D2_SPN_spn_iPoisson_offset_poisson,p.D2_SPN_spn_iPoisson_latency_poisson,p.D2_SPN_spn_iPoisson_f_poisson,p.D2_SPN_spn_iPoisson_fsigma_poisson,p.D2_SPN_spn_iPoisson_phi_poisson,p.D2_SPN_spn_iPoisson_connsigma_poisson,p.D2_SPN_spn_iPoisson_baseline_poisson,p.D2_SPN_spn_iPoisson_DC_poisson,p.D2_SPN_spn_iPoisson_AC_poisson,p.D2_SPN_spn_iPoisson_slopedutycycle_poisson,p.D2_SPN_spn_iPoisson_thresholddutycycle_poisson,p.D2_SPN_spn_iPoisson_tau_poisson,p.D2_SPN_spn_iPoisson_kick_poisson,T,p.D2_SPN_Npop);
D2_SPN_spn_ipfcPoisson_s_pfc_poisson = getPoissonDutyCycleGating(p.D2_SPN_spn_ipfcPoisson_onset_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_offset_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_latency_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_f_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_fsigma_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_phi_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_connsigma_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_baseline_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_DC_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_AC_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_slopedutycycle_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_thresholddutycycle_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_tau_pfc_poisson,p.D2_SPN_spn_ipfcPoisson_kick_pfc_poisson,T,p.D2_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_nRndConn_gaba =  round(p.D1_SPN_D1_SPN_spn_iGABA_conn_prob_gaba*p.D1_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_indPre_gaba =  round(1+(p.D1_SPN_Npop-1)*rand(p.D1_SPN_Npop,D1_SPN_D1_SPN_spn_iGABA_nRndConn_gaba));
D1_SPN_D1_SPN_spn_iGABA_netcon_gaba =  hist(D1_SPN_D1_SPN_spn_iGABA_indPre_gaba',1:p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_nRndConn_gaba =  round(p.D2_SPN_D1_SPN_spn_iGABA_conn_prob_gaba*p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_indPre_gaba =  round(1+(p.D1_SPN_Npop-1)*rand(p.D2_SPN_Npop,D2_SPN_D1_SPN_spn_iGABA_nRndConn_gaba));
D2_SPN_D1_SPN_spn_iGABA_netcon_gaba =  hist(D2_SPN_D1_SPN_spn_iGABA_indPre_gaba',1:p.D1_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_nRndConn_gaba =  round(p.D1_SPN_D2_SPN_spn_iGABA_conn_prob_gaba*p.D2_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_indPre_gaba =  round(1+(p.D2_SPN_Npop-1)*rand(p.D1_SPN_Npop,D1_SPN_D2_SPN_spn_iGABA_nRndConn_gaba));
D1_SPN_D2_SPN_spn_iGABA_netcon_gaba =  hist(D1_SPN_D2_SPN_spn_iGABA_indPre_gaba',1:p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_nRndConn_gaba =  round(p.D2_SPN_D2_SPN_spn_iGABA_conn_prob_gaba*p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_indPre_gaba =  round(1+(p.D2_SPN_Npop-1)*rand(p.D2_SPN_Npop,D2_SPN_D2_SPN_spn_iGABA_nRndConn_gaba));
D2_SPN_D2_SPN_spn_iGABA_netcon_gaba =  hist(D2_SPN_D2_SPN_spn_iGABA_indPre_gaba',1:p.D2_SPN_Npop);

% ------------------------------------------------------------
% Initial conditions:
% ------------------------------------------------------------
t=0; k=1;

% STATE_VARIABLES:
D1_SPN_V = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_V(1,:) =  -65+5*randn(1,p.D1_SPN_Npop);
D1_SPN_spn_iNa_m_na = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iNa_m_na(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_iNa_h_na = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iNa_h_na(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_iK_m_k = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iK_m_k(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_iM_m = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iM_m(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_iCa_m_cat = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iCa_m_cat(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_CaBuffer_caConcentration = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_CaBuffer_caConcentration(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D1_SPN_spn_iKca_m_kca = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iKca_m_kca(1,:) =  0 * ones(1,p.D1_SPN_Npop);
D2_SPN_V = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_V(1,:) =  -65+5*randn(1,p.D2_SPN_Npop);
D2_SPN_spn_iNa_m_na = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iNa_m_na(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_iNa_h_na = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iNa_h_na(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_iK_m_k = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iK_m_k(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_iM_m = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iM_m(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_iCa_m_cat = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iCa_m_cat(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_CaBuffer_caConcentration = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_CaBuffer_caConcentration(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D2_SPN_spn_iKca_m_kca = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iKca_m_kca(1,:) =  0 * ones(1,p.D2_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_d_gaba = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_d_gaba(1,:) =  ones(1,p.D1_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_s_gaba = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_s_gaba(1,:) =  p.D1_SPN_D1_SPN_spn_iGABA_IC_gaba+p.D1_SPN_D1_SPN_spn_iGABA_IC_noise_gaba.*rand(1,p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_d_gaba = zeros(nsamp,p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_d_gaba(1,:) =  ones(1,p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_s_gaba = zeros(nsamp,p.D1_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_s_gaba(1,:) =  p.D2_SPN_D1_SPN_spn_iGABA_IC_gaba+p.D2_SPN_D1_SPN_spn_iGABA_IC_noise_gaba.*rand(1,p.D1_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_d_gaba = zeros(nsamp,p.D2_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_d_gaba(1,:) =  ones(1,p.D2_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_s_gaba = zeros(nsamp,p.D2_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_s_gaba(1,:) =  p.D1_SPN_D2_SPN_spn_iGABA_IC_gaba+p.D1_SPN_D2_SPN_spn_iGABA_IC_noise_gaba.*rand(1,p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_d_gaba = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_d_gaba(1,:) =  ones(1,p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_s_gaba = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_s_gaba(1,:) =  p.D2_SPN_D2_SPN_spn_iGABA_IC_gaba+p.D2_SPN_D2_SPN_spn_iGABA_IC_noise_gaba.*rand(1,p.D2_SPN_Npop);

% MONITORS:
D1_SPN_spn_iNa_i_Na = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iNa_i_Na(1,:)=-p.D1_SPN_spn_iNa_g_na*D1_SPN_spn_iNa_m_na(1,:).^3.*D1_SPN_spn_iNa_h_na(1,:).*(D1_SPN_V(1,:)-p.D1_SPN_spn_iNa_E_na);
D1_SPN_spn_iK_i_k = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iK_i_k(1,:)=-p.D1_SPN_spn_iK_g_k*D1_SPN_spn_iK_m_k(1,:).^4.*(D1_SPN_V(1,:)-p.D1_SPN_spn_iK_E_k);
D1_SPN_spn_iLeak_i_l = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iLeak_i_l(1,:)=-p.D1_SPN_spn_iLeak_g_l*(D1_SPN_V(1,:)-p.D1_SPN_spn_iLeak_E_l);
D1_SPN_spn_iM_i_m = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iM_i_m(1,:)=-p.D1_SPN_spn_iM_g_m*D1_SPN_spn_iM_m(1,:).*(D1_SPN_V(1,:)-p.D1_SPN_spn_iM_E_m);
D1_SPN_spn_iCa_i_cat = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iCa_i_cat(1,:)=-p.D1_SPN_spn_iCa_g_cat*(D1_SPN_spn_iCa_m_cat(1,:).^2).*(D1_SPN_V(1,:)-p.D1_SPN_spn_iCa_E_cat);
D1_SPN_spn_iKca_i_kca = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iKca_i_kca(1,:)=-p.D1_SPN_spn_iKca_g_kca*D1_SPN_spn_iKca_m_kca(1,:).*(D1_SPN_V(1,:)-p.D1_SPN_spn_iKca_E_kca);
D1_SPN_spn_iPoisson_g_poisson = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iPoisson_g_poisson(1,:)=p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:);
D1_SPN_spn_iPoisson_I_poisson = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_iPoisson_I_poisson(1,:)=-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(1,:)-p.D1_SPN_spn_iPoisson_E_poisson);
D1_SPN_spn_ipfcPoisson_g_pfc_poisson = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_ipfcPoisson_g_pfc_poisson(1,:)=p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:);
D1_SPN_spn_ipfcPoisson_I_pfc_poisson = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_spn_ipfcPoisson_I_pfc_poisson(1,:)=-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(1,:)-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson);
D2_SPN_spn_iNa_i_Na = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iNa_i_Na(1,:)=-p.D2_SPN_spn_iNa_g_na*D2_SPN_spn_iNa_m_na(1,:).^3.*D2_SPN_spn_iNa_h_na(1,:).*(D2_SPN_V(1,:)-p.D2_SPN_spn_iNa_E_na);
D2_SPN_spn_iK_i_k = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iK_i_k(1,:)=-p.D2_SPN_spn_iK_g_k*D2_SPN_spn_iK_m_k(1,:).^4.*(D2_SPN_V(1,:)-p.D2_SPN_spn_iK_E_k);
D2_SPN_spn_iLeak_i_l = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iLeak_i_l(1,:)=-p.D2_SPN_spn_iLeak_g_l*(D2_SPN_V(1,:)-p.D2_SPN_spn_iLeak_E_l);
D2_SPN_spn_iM_i_m = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iM_i_m(1,:)=-p.D2_SPN_spn_iM_g_m*D2_SPN_spn_iM_m(1,:).*(D2_SPN_V(1,:)-p.D2_SPN_spn_iM_E_m);
D2_SPN_spn_iCa_i_cat = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iCa_i_cat(1,:)=-p.D2_SPN_spn_iCa_g_cat*(D2_SPN_spn_iCa_m_cat(1,:).^2).*(D2_SPN_V(1,:)-p.D2_SPN_spn_iCa_E_cat);
D2_SPN_spn_iKca_i_kca = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iKca_i_kca(1,:)=-p.D2_SPN_spn_iKca_g_kca*D2_SPN_spn_iKca_m_kca(1,:).*(D2_SPN_V(1,:)-p.D2_SPN_spn_iKca_E_kca);
D2_SPN_spn_iPoisson_g_poisson = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iPoisson_g_poisson(1,:)=p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:);
D2_SPN_spn_iPoisson_I_poisson = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_iPoisson_I_poisson(1,:)=-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(1,:)-p.D2_SPN_spn_iPoisson_E_poisson);
D2_SPN_spn_ipfcPoisson_g_pfc_poisson = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_ipfcPoisson_g_pfc_poisson(1,:)=p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:);
D2_SPN_spn_ipfcPoisson_I_pfc_poisson = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_spn_ipfcPoisson_I_pfc_poisson(1,:)=-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(1,:)-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson);
D1_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN(1,:)=-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(D1_SPN_D1_SPN_spn_iGABA_s_gaba(1,:)*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*(D1_SPN_V(1,:)-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba);
D2_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN(1,:)=-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(D2_SPN_D1_SPN_spn_iGABA_s_gaba(1,:)*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*(D2_SPN_V(1,:)-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba);
D1_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN = zeros(nsamp,p.D1_SPN_Npop);
D1_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN(1,:)=-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(D1_SPN_D2_SPN_spn_iGABA_s_gaba(1,:)*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*(D1_SPN_V(1,:)-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba);
D2_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN = zeros(nsamp,p.D2_SPN_Npop);
D2_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN(1,:)=-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(D2_SPN_D2_SPN_spn_iGABA_s_gaba(1,:)*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*(D2_SPN_V(1,:)-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba);

% ###########################################################
% Numerical integration:
% ###########################################################
n=2;
for k=2:ntime
  t=T(k-1);
  D1_SPN_V_k1 = ((((-p.D1_SPN_spn_iNa_g_na*D1_SPN_spn_iNa_m_na(n-1,:).^3.*D1_SPN_spn_iNa_h_na(n-1,:).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iNa_E_na))))+((((-p.D1_SPN_spn_iK_g_k*D1_SPN_spn_iK_m_k(n-1,:).^4.*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iK_E_k))))+((((-p.D1_SPN_spn_iLeak_g_l*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iLeak_E_l))))+((((-p.D1_SPN_spn_iM_g_m*D1_SPN_spn_iM_m(n-1,:).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iM_E_m))))+((((-p.D1_SPN_spn_iCa_g_cat*(D1_SPN_spn_iCa_m_cat(n-1,:).^2).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_E_cat))))+((((-p.D1_SPN_spn_iKca_g_kca*D1_SPN_spn_iKca_m_kca(n-1,:).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iKca_E_kca))))+((((-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iPoisson_E_poisson))))+((((-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((D1_SPN_V(n-1,:))-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((D1_SPN_V(n-1,:))-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D1_SPN_spn_iNa_m_na_k1 = ((0.32*(D1_SPN_V(n-1,:)+54)./(1-exp(-(D1_SPN_V(n-1,:)+54)/4)))).*(1-D1_SPN_spn_iNa_m_na(n-1,:))-((0.28*(D1_SPN_V(n-1,:)+27)./(exp((D1_SPN_V(n-1,:)+27)/5)-1))).*D1_SPN_spn_iNa_m_na(n-1,:);
  D1_SPN_spn_iNa_h_na_k1 = ((0.128*exp(-(D1_SPN_V(n-1,:)+50)/18))).*(1-D1_SPN_spn_iNa_h_na(n-1,:))-((4./(1+exp(-(D1_SPN_V(n-1,:)+27)/5)))).*D1_SPN_spn_iNa_h_na(n-1,:);
  D1_SPN_spn_iK_m_k_k1 = ((0.032*(D1_SPN_V(n-1,:)+52)./(1-exp(-(D1_SPN_V(n-1,:)+52)/5)))).*(1-D1_SPN_spn_iK_m_k(n-1,:))-((0.5*exp(-(D1_SPN_V(n-1,:)+57)/40))).*D1_SPN_spn_iK_m_k(n-1,:);
  D1_SPN_spn_iM_m_k1 = ((D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iM_vhalf_m)./(1-exp(-(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*(1-D1_SPN_spn_iM_m(n-1,:)) - ((-D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iM_vhalf_m)./(1-exp((D1_SPN_V(n-1,:)-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*D1_SPN_spn_iM_m(n-1,:);
  D1_SPN_spn_iCa_m_cat_k1 = (((((1.6./(1+exp(-.072*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-D1_SPN_spn_iCa_m_cat(n-1,:))./((1./(((1.6./(1+exp(-.072*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D1_SPN_spn_CaBuffer_caConcentration_k1 = -D1_SPN_spn_CaBuffer_caConcentration(n-1,:)/p.D1_SPN_spn_CaBuffer_tau_caConcentration + p.D1_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D1_SPN_spn_iCa_g_cat*(D1_SPN_spn_iCa_m_cat(n-1,:).^2).*(D1_SPN_V(n-1,:)-p.D1_SPN_spn_iCa_E_cat))))));
  D1_SPN_spn_iKca_m_kca_k1 = (((1./(1+exp(-(((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:)))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))-D1_SPN_spn_iKca_m_kca(n-1,:))./((p.D1_SPN_spn_iKca_tau_offset_kca-p.D1_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:)))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))));
  D2_SPN_V_k1 = ((((-p.D2_SPN_spn_iNa_g_na*D2_SPN_spn_iNa_m_na(n-1,:).^3.*D2_SPN_spn_iNa_h_na(n-1,:).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iNa_E_na))))+((((-p.D2_SPN_spn_iK_g_k*D2_SPN_spn_iK_m_k(n-1,:).^4.*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iK_E_k))))+((((-p.D2_SPN_spn_iLeak_g_l*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iLeak_E_l))))+((((-p.D2_SPN_spn_iM_g_m*D2_SPN_spn_iM_m(n-1,:).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iM_E_m))))+((((-p.D2_SPN_spn_iCa_g_cat*(D2_SPN_spn_iCa_m_cat(n-1,:).^2).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_E_cat))))+((((-p.D2_SPN_spn_iKca_g_kca*D2_SPN_spn_iKca_m_kca(n-1,:).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iKca_E_kca))))+((((-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iPoisson_E_poisson))))+((((-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((D2_SPN_V(n-1,:))-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((D2_SPN_V(n-1,:))-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D2_SPN_spn_iNa_m_na_k1 = ((0.32*(D2_SPN_V(n-1,:)+54)./(1-exp(-(D2_SPN_V(n-1,:)+54)/4)))).*(1-D2_SPN_spn_iNa_m_na(n-1,:))-((0.28*(D2_SPN_V(n-1,:)+27)./(exp((D2_SPN_V(n-1,:)+27)/5)-1))).*D2_SPN_spn_iNa_m_na(n-1,:);
  D2_SPN_spn_iNa_h_na_k1 = ((0.128*exp(-(D2_SPN_V(n-1,:)+50)/18))).*(1-D2_SPN_spn_iNa_h_na(n-1,:))-((4./(1+exp(-(D2_SPN_V(n-1,:)+27)/5)))).*D2_SPN_spn_iNa_h_na(n-1,:);
  D2_SPN_spn_iK_m_k_k1 = ((0.032*(D2_SPN_V(n-1,:)+52)./(1-exp(-(D2_SPN_V(n-1,:)+52)/5)))).*(1-D2_SPN_spn_iK_m_k(n-1,:))-((0.5*exp(-(D2_SPN_V(n-1,:)+57)/40))).*D2_SPN_spn_iK_m_k(n-1,:);
  D2_SPN_spn_iM_m_k1 = ((D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iM_vhalf_m)./(1-exp(-(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*(1-D2_SPN_spn_iM_m(n-1,:)) - ((-D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iM_vhalf_m)./(1-exp((D2_SPN_V(n-1,:)-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*D2_SPN_spn_iM_m(n-1,:);
  D2_SPN_spn_iCa_m_cat_k1 = (((((1.6./(1+exp(-.072*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-D2_SPN_spn_iCa_m_cat(n-1,:))./((1./(((1.6./(1+exp(-.072*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D2_SPN_spn_CaBuffer_caConcentration_k1 = -D2_SPN_spn_CaBuffer_caConcentration(n-1,:)/p.D2_SPN_spn_CaBuffer_tau_caConcentration + p.D2_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D2_SPN_spn_iCa_g_cat*(D2_SPN_spn_iCa_m_cat(n-1,:).^2).*(D2_SPN_V(n-1,:)-p.D2_SPN_spn_iCa_E_cat))))));
  D2_SPN_spn_iKca_m_kca_k1 = (((1./(1+exp(-(((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:)))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))-D2_SPN_spn_iKca_m_kca(n-1,:))./((p.D2_SPN_spn_iKca_tau_offset_kca-p.D2_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:)))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))));
  D1_SPN_D1_SPN_spn_iGABA_d_gaba_k1 = (1-D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:))./p.D1_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(D1_SPN_V(n-1,:)/4)).*D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:)*(p.D1_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D1_SPN_spn_iGABA_s_gaba_k1 = -D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)./p.D1_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(D1_SPN_V(n-1,:)/4)).*(1-D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)).*D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:);
  D2_SPN_D1_SPN_spn_iGABA_d_gaba_k1 = (1-D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:))./p.D2_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(D1_SPN_V(n-1,:)/4)).*D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:)*(p.D2_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D1_SPN_spn_iGABA_s_gaba_k1 = -D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)./p.D2_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(D1_SPN_V(n-1,:)/4)).*(1-D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)).*D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:);
  D1_SPN_D2_SPN_spn_iGABA_d_gaba_k1 = (1-D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:))./p.D1_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(D2_SPN_V(n-1,:)/4)).*D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:)*(p.D1_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D2_SPN_spn_iGABA_s_gaba_k1 = -D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)./p.D1_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(D2_SPN_V(n-1,:)/4)).*(1-D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)).*D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:);
  D2_SPN_D2_SPN_spn_iGABA_d_gaba_k1 = (1-D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:))./p.D2_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(D2_SPN_V(n-1,:)/4)).*D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:)*(p.D2_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D2_SPN_spn_iGABA_s_gaba_k1 = -D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)./p.D2_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(D2_SPN_V(n-1,:)/4)).*(1-D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)).*D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:);

  t = t + .5*dt;
  D1_SPN_V_k2 = ((((-p.D1_SPN_spn_iNa_g_na*((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k1)).^3.*((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k1)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iNa_E_na))))+((((-p.D1_SPN_spn_iK_g_k*((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k1)).^4.*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iK_E_k))))+((((-p.D1_SPN_spn_iLeak_g_l*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iLeak_E_l))))+((((-p.D1_SPN_spn_iM_g_m*((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k1)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iM_E_m))))+((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k1)).^2).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_E_cat))))+((((-p.D1_SPN_spn_iKca_g_kca*((D1_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D1_SPN_spn_iKca_m_kca_k1)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iKca_E_kca))))+((((-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iPoisson_E_poisson))))+((((-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k1))*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1)))-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k1))*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1)))-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D1_SPN_spn_iNa_m_na_k2 = ((0.32*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+54)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+54)/4)))).*(1-((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k1)))-((0.28*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+27)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+27)/5)-1))).*((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k1));
  D1_SPN_spn_iNa_h_na_k2 = ((0.128*exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+50)/18))).*(1-((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k1)))-((4./(1+exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+27)/5)))).*((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k1));
  D1_SPN_spn_iK_m_k_k2 = ((0.032*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+52)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+52)/5)))).*(1-((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k1)))-((0.5*exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))+57)/40))).*((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k1));
  D1_SPN_spn_iM_m_k2 = ((D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*(1-((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k1))) - ((-D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k1));
  D1_SPN_spn_iCa_m_cat_k2 = (((((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k1)))./((1./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D1_SPN_spn_CaBuffer_caConcentration_k2 = -((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k1))/p.D1_SPN_spn_CaBuffer_tau_caConcentration + p.D1_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k1)).^2).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))-p.D1_SPN_spn_iCa_E_cat))))));
  D1_SPN_spn_iKca_m_kca_k2 = (((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k1))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))-((D1_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D1_SPN_spn_iKca_m_kca_k1)))./((p.D1_SPN_spn_iKca_tau_offset_kca-p.D1_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k1))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))));
  D2_SPN_V_k2 = ((((-p.D2_SPN_spn_iNa_g_na*((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k1)).^3.*((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k1)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iNa_E_na))))+((((-p.D2_SPN_spn_iK_g_k*((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k1)).^4.*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iK_E_k))))+((((-p.D2_SPN_spn_iLeak_g_l*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iLeak_E_l))))+((((-p.D2_SPN_spn_iM_g_m*((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k1)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iM_E_m))))+((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k1)).^2).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_E_cat))))+((((-p.D2_SPN_spn_iKca_g_kca*((D2_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D2_SPN_spn_iKca_m_kca_k1)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iKca_E_kca))))+((((-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iPoisson_E_poisson))))+((((-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k1))*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1)))-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k1))*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1)))-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D2_SPN_spn_iNa_m_na_k2 = ((0.32*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+54)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+54)/4)))).*(1-((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k1)))-((0.28*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+27)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+27)/5)-1))).*((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k1));
  D2_SPN_spn_iNa_h_na_k2 = ((0.128*exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+50)/18))).*(1-((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k1)))-((4./(1+exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+27)/5)))).*((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k1));
  D2_SPN_spn_iK_m_k_k2 = ((0.032*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+52)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+52)/5)))).*(1-((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k1)))-((0.5*exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))+57)/40))).*((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k1));
  D2_SPN_spn_iM_m_k2 = ((D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*(1-((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k1))) - ((-D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k1));
  D2_SPN_spn_iCa_m_cat_k2 = (((((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k1)))./((1./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D2_SPN_spn_CaBuffer_caConcentration_k2 = -((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k1))/p.D2_SPN_spn_CaBuffer_tau_caConcentration + p.D2_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k1)).^2).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))-p.D2_SPN_spn_iCa_E_cat))))));
  D2_SPN_spn_iKca_m_kca_k2 = (((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k1))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))-((D2_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D2_SPN_spn_iKca_m_kca_k1)))./((p.D2_SPN_spn_iKca_tau_offset_kca-p.D2_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k1))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))));
  D1_SPN_D1_SPN_spn_iGABA_d_gaba_k2 = (1-((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k1)))./p.D1_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))/4)).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k1))*(p.D1_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D1_SPN_spn_iGABA_s_gaba_k2 = -((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k1))./p.D1_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))/4)).*(1-((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k1))).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k1));
  D2_SPN_D1_SPN_spn_iGABA_d_gaba_k2 = (1-((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k1)))./p.D2_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))/4)).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k1))*(p.D2_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D1_SPN_spn_iGABA_s_gaba_k2 = -((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k1))./p.D2_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k1))/4)).*(1-((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k1))).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k1));
  D1_SPN_D2_SPN_spn_iGABA_d_gaba_k2 = (1-((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k1)))./p.D1_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))/4)).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k1))*(p.D1_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D2_SPN_spn_iGABA_s_gaba_k2 = -((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k1))./p.D1_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))/4)).*(1-((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k1))).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k1));
  D2_SPN_D2_SPN_spn_iGABA_d_gaba_k2 = (1-((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k1)))./p.D2_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))/4)).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k1))*(p.D2_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D2_SPN_spn_iGABA_s_gaba_k2 = -((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k1))./p.D2_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k1))/4)).*(1-((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k1))).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k1));

  D1_SPN_V_k3 = ((((-p.D1_SPN_spn_iNa_g_na*((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k2)).^3.*((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k2)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iNa_E_na))))+((((-p.D1_SPN_spn_iK_g_k*((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k2)).^4.*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iK_E_k))))+((((-p.D1_SPN_spn_iLeak_g_l*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iLeak_E_l))))+((((-p.D1_SPN_spn_iM_g_m*((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k2)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iM_E_m))))+((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k2)).^2).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_E_cat))))+((((-p.D1_SPN_spn_iKca_g_kca*((D1_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D1_SPN_spn_iKca_m_kca_k2)).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iKca_E_kca))))+((((-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iPoisson_E_poisson))))+((((-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k2))*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2)))-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k2))*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2)))-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D1_SPN_spn_iNa_m_na_k3 = ((0.32*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+54)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+54)/4)))).*(1-((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k2)))-((0.28*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+27)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+27)/5)-1))).*((D1_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_m_na_k2));
  D1_SPN_spn_iNa_h_na_k3 = ((0.128*exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+50)/18))).*(1-((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k2)))-((4./(1+exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+27)/5)))).*((D1_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D1_SPN_spn_iNa_h_na_k2));
  D1_SPN_spn_iK_m_k_k3 = ((0.032*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+52)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+52)/5)))).*(1-((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k2)))-((0.5*exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))+57)/40))).*((D1_SPN_spn_iK_m_k(n-1,:) + .5*dt*D1_SPN_spn_iK_m_k_k2));
  D1_SPN_spn_iM_m_k3 = ((D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp(-(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*(1-((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k2))) - ((-D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*((D1_SPN_spn_iM_m(n-1,:) + .5*dt*D1_SPN_spn_iM_m_k2));
  D1_SPN_spn_iCa_m_cat_k3 = (((((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k2)))./((1./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D1_SPN_spn_CaBuffer_caConcentration_k3 = -((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k2))/p.D1_SPN_spn_CaBuffer_tau_caConcentration + p.D1_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D1_SPN_spn_iCa_m_cat_k2)).^2).*(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))-p.D1_SPN_spn_iCa_E_cat))))));
  D1_SPN_spn_iKca_m_kca_k3 = (((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k2))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))-((D1_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D1_SPN_spn_iKca_m_kca_k2)))./((p.D1_SPN_spn_iKca_tau_offset_kca-p.D1_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D1_SPN_spn_CaBuffer_caConcentration_k2))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))));
  D2_SPN_V_k3 = ((((-p.D2_SPN_spn_iNa_g_na*((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k2)).^3.*((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k2)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iNa_E_na))))+((((-p.D2_SPN_spn_iK_g_k*((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k2)).^4.*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iK_E_k))))+((((-p.D2_SPN_spn_iLeak_g_l*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iLeak_E_l))))+((((-p.D2_SPN_spn_iM_g_m*((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k2)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iM_E_m))))+((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k2)).^2).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_E_cat))))+((((-p.D2_SPN_spn_iKca_g_kca*((D2_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D2_SPN_spn_iKca_m_kca_k2)).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iKca_E_kca))))+((((-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iPoisson_E_poisson))))+((((-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k2))*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2)))-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k2))*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2)))-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D2_SPN_spn_iNa_m_na_k3 = ((0.32*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+54)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+54)/4)))).*(1-((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k2)))-((0.28*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+27)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+27)/5)-1))).*((D2_SPN_spn_iNa_m_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_m_na_k2));
  D2_SPN_spn_iNa_h_na_k3 = ((0.128*exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+50)/18))).*(1-((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k2)))-((4./(1+exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+27)/5)))).*((D2_SPN_spn_iNa_h_na(n-1,:) + .5*dt*D2_SPN_spn_iNa_h_na_k2));
  D2_SPN_spn_iK_m_k_k3 = ((0.032*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+52)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+52)/5)))).*(1-((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k2)))-((0.5*exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))+57)/40))).*((D2_SPN_spn_iK_m_k(n-1,:) + .5*dt*D2_SPN_spn_iK_m_k_k2));
  D2_SPN_spn_iM_m_k3 = ((D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp(-(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*(1-((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k2))) - ((-D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*((D2_SPN_spn_iM_m(n-1,:) + .5*dt*D2_SPN_spn_iM_m_k2));
  D2_SPN_spn_iCa_m_cat_k3 = (((((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k2)))./((1./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D2_SPN_spn_CaBuffer_caConcentration_k3 = -((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k2))/p.D2_SPN_spn_CaBuffer_tau_caConcentration + p.D2_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + .5*dt*D2_SPN_spn_iCa_m_cat_k2)).^2).*(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))-p.D2_SPN_spn_iCa_E_cat))))));
  D2_SPN_spn_iKca_m_kca_k3 = (((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k2))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))-((D2_SPN_spn_iKca_m_kca(n-1,:) + .5*dt*D2_SPN_spn_iKca_m_kca_k2)))./((p.D2_SPN_spn_iKca_tau_offset_kca-p.D2_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + .5*dt*D2_SPN_spn_CaBuffer_caConcentration_k2))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))));
  D1_SPN_D1_SPN_spn_iGABA_d_gaba_k3 = (1-((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k2)))./p.D1_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))/4)).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k2))*(p.D1_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D1_SPN_spn_iGABA_s_gaba_k3 = -((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k2))./p.D1_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))/4)).*(1-((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k2))).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k2));
  D2_SPN_D1_SPN_spn_iGABA_d_gaba_k3 = (1-((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k2)))./p.D2_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))/4)).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k2))*(p.D2_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D1_SPN_spn_iGABA_s_gaba_k3 = -((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k2))./p.D2_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + .5*dt*D1_SPN_V_k2))/4)).*(1-((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k2))).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k2));
  D1_SPN_D2_SPN_spn_iGABA_d_gaba_k3 = (1-((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k2)))./p.D1_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))/4)).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k2))*(p.D1_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D2_SPN_spn_iGABA_s_gaba_k3 = -((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k2))./p.D1_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))/4)).*(1-((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k2))).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k2));
  D2_SPN_D2_SPN_spn_iGABA_d_gaba_k3 = (1-((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k2)))./p.D2_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))/4)).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k2))*(p.D2_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D2_SPN_spn_iGABA_s_gaba_k3 = -((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k2))./p.D2_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + .5*dt*D2_SPN_V_k2))/4)).*(1-((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k2))).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + .5*dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k2));

  t = t + .5*dt;
  D1_SPN_V_k4 = ((((-p.D1_SPN_spn_iNa_g_na*((D1_SPN_spn_iNa_m_na(n-1,:) + dt*D1_SPN_spn_iNa_m_na_k3)).^3.*((D1_SPN_spn_iNa_h_na(n-1,:) + dt*D1_SPN_spn_iNa_h_na_k3)).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iNa_E_na))))+((((-p.D1_SPN_spn_iK_g_k*((D1_SPN_spn_iK_m_k(n-1,:) + dt*D1_SPN_spn_iK_m_k_k3)).^4.*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iK_E_k))))+((((-p.D1_SPN_spn_iLeak_g_l*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iLeak_E_l))))+((((-p.D1_SPN_spn_iM_g_m*((D1_SPN_spn_iM_m(n-1,:) + dt*D1_SPN_spn_iM_m_k3)).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iM_E_m))))+((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + dt*D1_SPN_spn_iCa_m_cat_k3)).^2).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_E_cat))))+((((-p.D1_SPN_spn_iKca_g_kca*((D1_SPN_spn_iKca_m_kca(n-1,:) + dt*D1_SPN_spn_iKca_m_kca_k3)).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iKca_E_kca))))+((((-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iPoisson_E_poisson))))+((((-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k3))*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3)))-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k3))*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3)))-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D1_SPN_spn_iNa_m_na_k4 = ((0.32*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+54)./(1-exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+54)/4)))).*(1-((D1_SPN_spn_iNa_m_na(n-1,:) + dt*D1_SPN_spn_iNa_m_na_k3)))-((0.28*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+27)./(exp((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+27)/5)-1))).*((D1_SPN_spn_iNa_m_na(n-1,:) + dt*D1_SPN_spn_iNa_m_na_k3));
  D1_SPN_spn_iNa_h_na_k4 = ((0.128*exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+50)/18))).*(1-((D1_SPN_spn_iNa_h_na(n-1,:) + dt*D1_SPN_spn_iNa_h_na_k3)))-((4./(1+exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+27)/5)))).*((D1_SPN_spn_iNa_h_na(n-1,:) + dt*D1_SPN_spn_iNa_h_na_k3));
  D1_SPN_spn_iK_m_k_k4 = ((0.032*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+52)./(1-exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+52)/5)))).*(1-((D1_SPN_spn_iK_m_k(n-1,:) + dt*D1_SPN_spn_iK_m_k_k3)))-((0.5*exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))+57)/40))).*((D1_SPN_spn_iK_m_k(n-1,:) + dt*D1_SPN_spn_iK_m_k_k3));
  D1_SPN_spn_iM_m_k4 = ((D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp(-(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*(1-((D1_SPN_spn_iM_m(n-1,:) + dt*D1_SPN_spn_iM_m_k3))) - ((-D1_SPN_spn_iM_Qs_m*p.D1_SPN_spn_iM_Fnum_m*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iM_vhalf_m)./(1-exp((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iM_vhalf_m)/p.D1_SPN_spn_iM_vslope_m)))).*((D1_SPN_spn_iM_m(n-1,:) + dt*D1_SPN_spn_iM_m_k3));
  D1_SPN_spn_iCa_m_cat_k4 = (((((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D1_SPN_spn_iCa_m_cat(n-1,:) + dt*D1_SPN_spn_iCa_m_cat_k3)))./((1./(((1.6./(1+exp(-.072*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-51.1)./(exp((((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D1_SPN_spn_CaBuffer_caConcentration_k4 = -((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D1_SPN_spn_CaBuffer_caConcentration_k3))/p.D1_SPN_spn_CaBuffer_tau_caConcentration + p.D1_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D1_SPN_spn_iCa_g_cat*(((D1_SPN_spn_iCa_m_cat(n-1,:) + dt*D1_SPN_spn_iCa_m_cat_k3)).^2).*(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))-p.D1_SPN_spn_iCa_E_cat))))));
  D1_SPN_spn_iKca_m_kca_k4 = (((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D1_SPN_spn_CaBuffer_caConcentration_k3))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))-((D1_SPN_spn_iKca_m_kca(n-1,:) + dt*D1_SPN_spn_iKca_m_kca_k3)))./((p.D1_SPN_spn_iKca_tau_offset_kca-p.D1_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D1_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D1_SPN_spn_CaBuffer_caConcentration_k3))))))-p.D1_SPN_spn_iKca_caConcentration_offset_kca)/p.D1_SPN_spn_iKca_caConcentration_slope_kca))))));
  D2_SPN_V_k4 = ((((-p.D2_SPN_spn_iNa_g_na*((D2_SPN_spn_iNa_m_na(n-1,:) + dt*D2_SPN_spn_iNa_m_na_k3)).^3.*((D2_SPN_spn_iNa_h_na(n-1,:) + dt*D2_SPN_spn_iNa_h_na_k3)).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iNa_E_na))))+((((-p.D2_SPN_spn_iK_g_k*((D2_SPN_spn_iK_m_k(n-1,:) + dt*D2_SPN_spn_iK_m_k_k3)).^4.*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iK_E_k))))+((((-p.D2_SPN_spn_iLeak_g_l*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iLeak_E_l))))+((((-p.D2_SPN_spn_iM_g_m*((D2_SPN_spn_iM_m(n-1,:) + dt*D2_SPN_spn_iM_m_k3)).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iM_E_m))))+((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + dt*D2_SPN_spn_iCa_m_cat_k3)).^2).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_E_cat))))+((((-p.D2_SPN_spn_iKca_g_kca*((D2_SPN_spn_iKca_m_kca(n-1,:) + dt*D2_SPN_spn_iKca_m_kca_k3)).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iKca_E_kca))))+((((-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iPoisson_E_poisson))))+((((-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson))))+((((-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k3))*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3)))-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba))))+((((-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k3))*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3)))-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba))))))))))))));
  D2_SPN_spn_iNa_m_na_k4 = ((0.32*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+54)./(1-exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+54)/4)))).*(1-((D2_SPN_spn_iNa_m_na(n-1,:) + dt*D2_SPN_spn_iNa_m_na_k3)))-((0.28*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+27)./(exp((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+27)/5)-1))).*((D2_SPN_spn_iNa_m_na(n-1,:) + dt*D2_SPN_spn_iNa_m_na_k3));
  D2_SPN_spn_iNa_h_na_k4 = ((0.128*exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+50)/18))).*(1-((D2_SPN_spn_iNa_h_na(n-1,:) + dt*D2_SPN_spn_iNa_h_na_k3)))-((4./(1+exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+27)/5)))).*((D2_SPN_spn_iNa_h_na(n-1,:) + dt*D2_SPN_spn_iNa_h_na_k3));
  D2_SPN_spn_iK_m_k_k4 = ((0.032*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+52)./(1-exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+52)/5)))).*(1-((D2_SPN_spn_iK_m_k(n-1,:) + dt*D2_SPN_spn_iK_m_k_k3)))-((0.5*exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))+57)/40))).*((D2_SPN_spn_iK_m_k(n-1,:) + dt*D2_SPN_spn_iK_m_k_k3));
  D2_SPN_spn_iM_m_k4 = ((D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp(-(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*(1-((D2_SPN_spn_iM_m(n-1,:) + dt*D2_SPN_spn_iM_m_k3))) - ((-D2_SPN_spn_iM_Qs_m*p.D2_SPN_spn_iM_Fnum_m*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iM_vhalf_m)./(1-exp((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iM_vhalf_m)/p.D2_SPN_spn_iM_vslope_m)))).*((D2_SPN_spn_iM_m(n-1,:) + dt*D2_SPN_spn_iM_m_k3));
  D2_SPN_spn_iCa_m_cat_k4 = (((((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-65)))))./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))))-((D2_SPN_spn_iCa_m_cat(n-1,:) + dt*D2_SPN_spn_iCa_m_cat_k3)))./((1./(((1.6./(1+exp(-.072*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-65)))))+((0.02*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-51.1)./(exp((((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_offset_cat-51.1)/5)-1))))));
  D2_SPN_spn_CaBuffer_caConcentration_k4 = -((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D2_SPN_spn_CaBuffer_caConcentration_k3))/p.D2_SPN_spn_CaBuffer_tau_caConcentration + p.D2_SPN_spn_CaBuffer_caf_caConcentration.*(((((-p.D2_SPN_spn_iCa_g_cat*(((D2_SPN_spn_iCa_m_cat(n-1,:) + dt*D2_SPN_spn_iCa_m_cat_k3)).^2).*(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))-p.D2_SPN_spn_iCa_E_cat))))));
  D2_SPN_spn_iKca_m_kca_k4 = (((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D2_SPN_spn_CaBuffer_caConcentration_k3))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))-((D2_SPN_spn_iKca_m_kca(n-1,:) + dt*D2_SPN_spn_iKca_m_kca_k3)))./((p.D2_SPN_spn_iKca_tau_offset_kca-p.D2_SPN_spn_iKca_tau_scaling_kca*((1./(1+exp(-(((((((D2_SPN_spn_CaBuffer_caConcentration(n-1,:) + dt*D2_SPN_spn_CaBuffer_caConcentration_k3))))))-p.D2_SPN_spn_iKca_caConcentration_offset_kca)/p.D2_SPN_spn_iKca_caConcentration_slope_kca))))));
  D1_SPN_D1_SPN_spn_iGABA_d_gaba_k4 = (1-((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k3)))./p.D1_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))/4)).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k3))*(p.D1_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D1_SPN_spn_iGABA_s_gaba_k4 = -((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k3))./p.D1_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))/4)).*(1-((D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_s_gaba_k3))).*((D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D1_SPN_spn_iGABA_d_gaba_k3));
  D2_SPN_D1_SPN_spn_iGABA_d_gaba_k4 = (1-((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k3)))./p.D2_SPN_D1_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D1_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))/4)).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k3))*(p.D2_SPN_D1_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D1_SPN_spn_iGABA_s_gaba_k4 = -((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k3))./p.D2_SPN_D1_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D1_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D1_SPN_V(n-1,:) + dt*D1_SPN_V_k3))/4)).*(1-((D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_s_gaba_k3))).*((D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D1_SPN_spn_iGABA_d_gaba_k3));
  D1_SPN_D2_SPN_spn_iGABA_d_gaba_k4 = (1-((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k3)))./p.D1_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D1_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))/4)).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k3))*(p.D1_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D1_SPN_D2_SPN_spn_iGABA_s_gaba_k4 = -((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k3))./p.D1_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D1_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))/4)).*(1-((D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_s_gaba_k3))).*((D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D1_SPN_D2_SPN_spn_iGABA_d_gaba_k3));
  D2_SPN_D2_SPN_spn_iGABA_d_gaba_k4 = (1-((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k3)))./p.D2_SPN_D2_SPN_spn_iGABA_tauD_gaba + 0.5*p.D2_SPN_D2_SPN_spn_iGABA_alphaD_gaba*(1+tanh(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))/4)).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k3))*(p.D2_SPN_D2_SPN_spn_iGABA_deltaD_gaba-1);
  D2_SPN_D2_SPN_spn_iGABA_s_gaba_k4 = -((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k3))./p.D2_SPN_D2_SPN_spn_iGABA_tau_gaba + 2*p.D2_SPN_D2_SPN_spn_iGABA_alpha_gaba*(1+tanh(((D2_SPN_V(n-1,:) + dt*D2_SPN_V_k3))/4)).*(1-((D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_s_gaba_k3))).*((D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:) + dt*D2_SPN_D2_SPN_spn_iGABA_d_gaba_k3));

  % ------------------------------------------------------------
  % Update state variables:
  % ------------------------------------------------------------
  D1_SPN_V(n,:) = D1_SPN_V(n-1,:)+(dt/6)*(D1_SPN_V_k1 + 2*(D1_SPN_V_k2 + D1_SPN_V_k3) + D1_SPN_V_k4);
  D1_SPN_spn_iNa_m_na(n,:) = D1_SPN_spn_iNa_m_na(n-1,:)+(dt/6)*(D1_SPN_spn_iNa_m_na_k1 + 2*(D1_SPN_spn_iNa_m_na_k2 + D1_SPN_spn_iNa_m_na_k3) + D1_SPN_spn_iNa_m_na_k4);
  D1_SPN_spn_iNa_h_na(n,:) = D1_SPN_spn_iNa_h_na(n-1,:)+(dt/6)*(D1_SPN_spn_iNa_h_na_k1 + 2*(D1_SPN_spn_iNa_h_na_k2 + D1_SPN_spn_iNa_h_na_k3) + D1_SPN_spn_iNa_h_na_k4);
  D1_SPN_spn_iK_m_k(n,:) = D1_SPN_spn_iK_m_k(n-1,:)+(dt/6)*(D1_SPN_spn_iK_m_k_k1 + 2*(D1_SPN_spn_iK_m_k_k2 + D1_SPN_spn_iK_m_k_k3) + D1_SPN_spn_iK_m_k_k4);
  D1_SPN_spn_iM_m(n,:) = D1_SPN_spn_iM_m(n-1,:)+(dt/6)*(D1_SPN_spn_iM_m_k1 + 2*(D1_SPN_spn_iM_m_k2 + D1_SPN_spn_iM_m_k3) + D1_SPN_spn_iM_m_k4);
  D1_SPN_spn_iCa_m_cat(n,:) = D1_SPN_spn_iCa_m_cat(n-1,:)+(dt/6)*(D1_SPN_spn_iCa_m_cat_k1 + 2*(D1_SPN_spn_iCa_m_cat_k2 + D1_SPN_spn_iCa_m_cat_k3) + D1_SPN_spn_iCa_m_cat_k4);
  D1_SPN_spn_CaBuffer_caConcentration(n,:) = D1_SPN_spn_CaBuffer_caConcentration(n-1,:)+(dt/6)*(D1_SPN_spn_CaBuffer_caConcentration_k1 + 2*(D1_SPN_spn_CaBuffer_caConcentration_k2 + D1_SPN_spn_CaBuffer_caConcentration_k3) + D1_SPN_spn_CaBuffer_caConcentration_k4);
  D1_SPN_spn_iKca_m_kca(n,:) = D1_SPN_spn_iKca_m_kca(n-1,:)+(dt/6)*(D1_SPN_spn_iKca_m_kca_k1 + 2*(D1_SPN_spn_iKca_m_kca_k2 + D1_SPN_spn_iKca_m_kca_k3) + D1_SPN_spn_iKca_m_kca_k4);
  D2_SPN_V(n,:) = D2_SPN_V(n-1,:)+(dt/6)*(D2_SPN_V_k1 + 2*(D2_SPN_V_k2 + D2_SPN_V_k3) + D2_SPN_V_k4);
  D2_SPN_spn_iNa_m_na(n,:) = D2_SPN_spn_iNa_m_na(n-1,:)+(dt/6)*(D2_SPN_spn_iNa_m_na_k1 + 2*(D2_SPN_spn_iNa_m_na_k2 + D2_SPN_spn_iNa_m_na_k3) + D2_SPN_spn_iNa_m_na_k4);
  D2_SPN_spn_iNa_h_na(n,:) = D2_SPN_spn_iNa_h_na(n-1,:)+(dt/6)*(D2_SPN_spn_iNa_h_na_k1 + 2*(D2_SPN_spn_iNa_h_na_k2 + D2_SPN_spn_iNa_h_na_k3) + D2_SPN_spn_iNa_h_na_k4);
  D2_SPN_spn_iK_m_k(n,:) = D2_SPN_spn_iK_m_k(n-1,:)+(dt/6)*(D2_SPN_spn_iK_m_k_k1 + 2*(D2_SPN_spn_iK_m_k_k2 + D2_SPN_spn_iK_m_k_k3) + D2_SPN_spn_iK_m_k_k4);
  D2_SPN_spn_iM_m(n,:) = D2_SPN_spn_iM_m(n-1,:)+(dt/6)*(D2_SPN_spn_iM_m_k1 + 2*(D2_SPN_spn_iM_m_k2 + D2_SPN_spn_iM_m_k3) + D2_SPN_spn_iM_m_k4);
  D2_SPN_spn_iCa_m_cat(n,:) = D2_SPN_spn_iCa_m_cat(n-1,:)+(dt/6)*(D2_SPN_spn_iCa_m_cat_k1 + 2*(D2_SPN_spn_iCa_m_cat_k2 + D2_SPN_spn_iCa_m_cat_k3) + D2_SPN_spn_iCa_m_cat_k4);
  D2_SPN_spn_CaBuffer_caConcentration(n,:) = D2_SPN_spn_CaBuffer_caConcentration(n-1,:)+(dt/6)*(D2_SPN_spn_CaBuffer_caConcentration_k1 + 2*(D2_SPN_spn_CaBuffer_caConcentration_k2 + D2_SPN_spn_CaBuffer_caConcentration_k3) + D2_SPN_spn_CaBuffer_caConcentration_k4);
  D2_SPN_spn_iKca_m_kca(n,:) = D2_SPN_spn_iKca_m_kca(n-1,:)+(dt/6)*(D2_SPN_spn_iKca_m_kca_k1 + 2*(D2_SPN_spn_iKca_m_kca_k2 + D2_SPN_spn_iKca_m_kca_k3) + D2_SPN_spn_iKca_m_kca_k4);
  D1_SPN_D1_SPN_spn_iGABA_d_gaba(n,:) = D1_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:)+(dt/6)*(D1_SPN_D1_SPN_spn_iGABA_d_gaba_k1 + 2*(D1_SPN_D1_SPN_spn_iGABA_d_gaba_k2 + D1_SPN_D1_SPN_spn_iGABA_d_gaba_k3) + D1_SPN_D1_SPN_spn_iGABA_d_gaba_k4);
  D1_SPN_D1_SPN_spn_iGABA_s_gaba(n,:) = D1_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)+(dt/6)*(D1_SPN_D1_SPN_spn_iGABA_s_gaba_k1 + 2*(D1_SPN_D1_SPN_spn_iGABA_s_gaba_k2 + D1_SPN_D1_SPN_spn_iGABA_s_gaba_k3) + D1_SPN_D1_SPN_spn_iGABA_s_gaba_k4);
  D2_SPN_D1_SPN_spn_iGABA_d_gaba(n,:) = D2_SPN_D1_SPN_spn_iGABA_d_gaba(n-1,:)+(dt/6)*(D2_SPN_D1_SPN_spn_iGABA_d_gaba_k1 + 2*(D2_SPN_D1_SPN_spn_iGABA_d_gaba_k2 + D2_SPN_D1_SPN_spn_iGABA_d_gaba_k3) + D2_SPN_D1_SPN_spn_iGABA_d_gaba_k4);
  D2_SPN_D1_SPN_spn_iGABA_s_gaba(n,:) = D2_SPN_D1_SPN_spn_iGABA_s_gaba(n-1,:)+(dt/6)*(D2_SPN_D1_SPN_spn_iGABA_s_gaba_k1 + 2*(D2_SPN_D1_SPN_spn_iGABA_s_gaba_k2 + D2_SPN_D1_SPN_spn_iGABA_s_gaba_k3) + D2_SPN_D1_SPN_spn_iGABA_s_gaba_k4);
  D1_SPN_D2_SPN_spn_iGABA_d_gaba(n,:) = D1_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:)+(dt/6)*(D1_SPN_D2_SPN_spn_iGABA_d_gaba_k1 + 2*(D1_SPN_D2_SPN_spn_iGABA_d_gaba_k2 + D1_SPN_D2_SPN_spn_iGABA_d_gaba_k3) + D1_SPN_D2_SPN_spn_iGABA_d_gaba_k4);
  D1_SPN_D2_SPN_spn_iGABA_s_gaba(n,:) = D1_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)+(dt/6)*(D1_SPN_D2_SPN_spn_iGABA_s_gaba_k1 + 2*(D1_SPN_D2_SPN_spn_iGABA_s_gaba_k2 + D1_SPN_D2_SPN_spn_iGABA_s_gaba_k3) + D1_SPN_D2_SPN_spn_iGABA_s_gaba_k4);
  D2_SPN_D2_SPN_spn_iGABA_d_gaba(n,:) = D2_SPN_D2_SPN_spn_iGABA_d_gaba(n-1,:)+(dt/6)*(D2_SPN_D2_SPN_spn_iGABA_d_gaba_k1 + 2*(D2_SPN_D2_SPN_spn_iGABA_d_gaba_k2 + D2_SPN_D2_SPN_spn_iGABA_d_gaba_k3) + D2_SPN_D2_SPN_spn_iGABA_d_gaba_k4);
  D2_SPN_D2_SPN_spn_iGABA_s_gaba(n,:) = D2_SPN_D2_SPN_spn_iGABA_s_gaba(n-1,:)+(dt/6)*(D2_SPN_D2_SPN_spn_iGABA_s_gaba_k1 + 2*(D2_SPN_D2_SPN_spn_iGABA_s_gaba_k2 + D2_SPN_D2_SPN_spn_iGABA_s_gaba_k3) + D2_SPN_D2_SPN_spn_iGABA_s_gaba_k4);

  % ------------------------------------------------------------
  % Update monitors:
  % ------------------------------------------------------------
  D1_SPN_spn_iNa_i_Na(n,:)=-p.D1_SPN_spn_iNa_g_na*D1_SPN_spn_iNa_m_na(n,:).^3.*D1_SPN_spn_iNa_h_na(n,:).*(D1_SPN_V(n,:)-p.D1_SPN_spn_iNa_E_na);
  D1_SPN_spn_iK_i_k(n,:)=-p.D1_SPN_spn_iK_g_k*D1_SPN_spn_iK_m_k(n,:).^4.*(D1_SPN_V(n,:)-p.D1_SPN_spn_iK_E_k);
  D1_SPN_spn_iLeak_i_l(n,:)=-p.D1_SPN_spn_iLeak_g_l*(D1_SPN_V(n,:)-p.D1_SPN_spn_iLeak_E_l);
  D1_SPN_spn_iM_i_m(n,:)=-p.D1_SPN_spn_iM_g_m*D1_SPN_spn_iM_m(n,:).*(D1_SPN_V(n,:)-p.D1_SPN_spn_iM_E_m);
  D1_SPN_spn_iCa_i_cat(n,:)=-p.D1_SPN_spn_iCa_g_cat*(D1_SPN_spn_iCa_m_cat(n,:).^2).*(D1_SPN_V(n,:)-p.D1_SPN_spn_iCa_E_cat);
  D1_SPN_spn_iKca_i_kca(n,:)=-p.D1_SPN_spn_iKca_g_kca*D1_SPN_spn_iKca_m_kca(n,:).*(D1_SPN_V(n,:)-p.D1_SPN_spn_iKca_E_kca);
  D1_SPN_spn_iPoisson_g_poisson(n,:)=p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:);
  D1_SPN_spn_iPoisson_I_poisson(n,:)=-((p.D1_SPN_spn_iPoisson_g_poisson.*D1_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(n,:)-p.D1_SPN_spn_iPoisson_E_poisson);
  D1_SPN_spn_ipfcPoisson_g_pfc_poisson(n,:)=p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:);
  D1_SPN_spn_ipfcPoisson_I_pfc_poisson(n,:)=-((p.D1_SPN_spn_ipfcPoisson_g_pfc_poisson.*D1_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D1_SPN_V(n,:)-p.D1_SPN_spn_ipfcPoisson_E_pfc_poisson);
  D2_SPN_spn_iNa_i_Na(n,:)=-p.D2_SPN_spn_iNa_g_na*D2_SPN_spn_iNa_m_na(n,:).^3.*D2_SPN_spn_iNa_h_na(n,:).*(D2_SPN_V(n,:)-p.D2_SPN_spn_iNa_E_na);
  D2_SPN_spn_iK_i_k(n,:)=-p.D2_SPN_spn_iK_g_k*D2_SPN_spn_iK_m_k(n,:).^4.*(D2_SPN_V(n,:)-p.D2_SPN_spn_iK_E_k);
  D2_SPN_spn_iLeak_i_l(n,:)=-p.D2_SPN_spn_iLeak_g_l*(D2_SPN_V(n,:)-p.D2_SPN_spn_iLeak_E_l);
  D2_SPN_spn_iM_i_m(n,:)=-p.D2_SPN_spn_iM_g_m*D2_SPN_spn_iM_m(n,:).*(D2_SPN_V(n,:)-p.D2_SPN_spn_iM_E_m);
  D2_SPN_spn_iCa_i_cat(n,:)=-p.D2_SPN_spn_iCa_g_cat*(D2_SPN_spn_iCa_m_cat(n,:).^2).*(D2_SPN_V(n,:)-p.D2_SPN_spn_iCa_E_cat);
  D2_SPN_spn_iKca_i_kca(n,:)=-p.D2_SPN_spn_iKca_g_kca*D2_SPN_spn_iKca_m_kca(n,:).*(D2_SPN_V(n,:)-p.D2_SPN_spn_iKca_E_kca);
  D2_SPN_spn_iPoisson_g_poisson(n,:)=p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:);
  D2_SPN_spn_iPoisson_I_poisson(n,:)=-((p.D2_SPN_spn_iPoisson_g_poisson.*D2_SPN_spn_iPoisson_s_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(n,:)-p.D2_SPN_spn_iPoisson_E_poisson);
  D2_SPN_spn_ipfcPoisson_g_pfc_poisson(n,:)=p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:);
  D2_SPN_spn_ipfcPoisson_I_pfc_poisson(n,:)=-((p.D2_SPN_spn_ipfcPoisson_g_pfc_poisson.*D2_SPN_spn_ipfcPoisson_s_pfc_poisson(1+floor(t/(0.5*dt)),:))).*(D2_SPN_V(n,:)-p.D2_SPN_spn_ipfcPoisson_E_pfc_poisson);
  D1_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN(n,:)=-p.D1_SPN_D1_SPN_spn_iGABA_g_gaba.*(D1_SPN_D1_SPN_spn_iGABA_s_gaba(n,:)*D1_SPN_D1_SPN_spn_iGABA_netcon_gaba).*(D1_SPN_V(n,:)-p.D1_SPN_D1_SPN_spn_iGABA_E_gaba);
  D2_SPN_D1_SPN_spn_iGABA_i_gabaRecSPN(n,:)=-p.D2_SPN_D1_SPN_spn_iGABA_g_gaba.*(D2_SPN_D1_SPN_spn_iGABA_s_gaba(n,:)*D2_SPN_D1_SPN_spn_iGABA_netcon_gaba).*(D2_SPN_V(n,:)-p.D2_SPN_D1_SPN_spn_iGABA_E_gaba);
  D1_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN(n,:)=-p.D1_SPN_D2_SPN_spn_iGABA_g_gaba.*(D1_SPN_D2_SPN_spn_iGABA_s_gaba(n,:)*D1_SPN_D2_SPN_spn_iGABA_netcon_gaba).*(D1_SPN_V(n,:)-p.D1_SPN_D2_SPN_spn_iGABA_E_gaba);
  D2_SPN_D2_SPN_spn_iGABA_i_gabaRecSPN(n,:)=-p.D2_SPN_D2_SPN_spn_iGABA_g_gaba.*(D2_SPN_D2_SPN_spn_iGABA_s_gaba(n,:)*D2_SPN_D2_SPN_spn_iGABA_netcon_gaba).*(D2_SPN_V(n,:)-p.D2_SPN_D2_SPN_spn_iGABA_E_gaba);
  n=n+1;
end

T=T(1:downsample_factor:ntime);

end
